const users = [
    {
        id: '410544b2-4001-4271-9855-fec4b6a6442a',
        name: 'User',
        email: 'user@gmail.com',
        password: '12345',
    },
];

const products = [
    {
        id: 1,
        imageSrc: "https://3.bp.blogspot.com/-EdcWh_lGhoU/UZIQqHwwIjI/AAAAAAAAAwA/TZVxHQoqDa0/s1600/High-Heels-Fashion-2013.jpg",
        name: "High Heels",
        price: 24000,
        discount: 10,
        qty: null,
        rating: 4,
        reviewCount: 209,
        description: "Key features: <br /> Heel height: 10.5 <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women shoes, delicate, thin, sexy, transparent high heels",
        detail: "Note: <br /> Please purchase the shoes according to the actual foot length. <br /> if your feet thick, relatively wide please buy one size larger shoe size <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 1,
        categoryName: "shoes",
        stock: 2,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-black", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "EU 36", inStock: true },
            { name: "EU 37", inStock: true },
            { name: "EU 38", inStock: true },
            { name: "EU 39", inStock: true },
            { name: "EU 40", inStock: true },
            { name: "EU 41", inStock: true },
            { name: "EU 42", inStock: true },
            { name: "EU 43", inStock: false },
        ],
    },
    {
        id: 2,
        imageSrc: "https://www.periodlink.com/wp-content/uploads/2023/01/gown-739sbb-1.jpg",
        name: "Wedding Gown",
        price: 95000,
        discount: 5,
        qty: null,
        rating: 4,
        reviewCount: 9,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 2,
        categoryName: "clothes",
        stock: 2,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Red", class: "bg-red-500", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-black", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "S", inStock: true },
            { name: "M", inStock: true },
            { name: "L", inStock: false },
            { name: "XL", inStock: true },
        ],
    },
    {
        id: 3,
        imageSrc: "https://img.ep-cdn.com/i/500/500/nc/ncswkgzptaoidvrjhfqe/defacto-woman-beret-hat-cene.jpg",
        name: "Defacto Woman Casual Hat",
        price: 5000,
        discount: 0,
        qty: null,
        rating: 4,
        reviewCount: 99,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 3,
        categoryName: "accesories",
        stock: 8,
        colors: [
            { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
            { name: "Pink", class: "bg-pink-400", selectedClass: "ring-gray-400" },
            { name: "Yellow", class: "bg-yellow-500", selectedClass: "ring-gray-900" },
        ],
    },
    {
        id: 4,
        imageSrc: "https://tse4.mm.bing.net/th/id/OIP.4FT3Vz5C1oyaBQUOv-I6oQHaG5?rs=1&pid=ImgDetMain&o=7&rm=3",
        name: "Cross Body Bag",
        price: 15000,
        discount: 0,
        qty: null,
        rating: 5,
        reviewCount: 453,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 4,
        categoryName: "bags",
        stock: 10,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Orange", class: "bg-orange-400", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
    },
    {
        id: 5,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/36/4213512/1.jpg?4157",
        name: "Ladies Fashion Heel Slippers",
        price: 28000,
        discount: 0,
        qty: null,
        rating: 4,
        reviewCount: 29,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 1,
        categoryName: "shoes",
        stock: 2,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Green", class: "bg-gren-500", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "EU 37", inStock: true },
            { name: "EU 38", inStock: true },
            { name: "EU 39", inStock: true },
            { name: "EU 40", inStock: true },
        ],
    },
    {
        id: 6,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/82/658597/1.jpg?9713",
        name: "Office Lady Casual Hot Dress",
        price: 20000,
        discount: 10,
        qty: null,
        rating: 4,
        reviewCount: 20,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 2,
        categoryName: "clothes",
        stock: 2,
        sizes: [
            { name: "XXS", inStock: true },
            { name: "XS", inStock: true },
            { name: "S", inStock: true },
            { name: "M", inStock: true },
            { name: "L", inStock: true },
            { name: "XL", inStock: true },
            { name: "XXL", inStock: true },
            { name: "XXXL", inStock: false },
        ],
    },
    {
        id: 7,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/72/9938293/1.jpg?9327",
        name: "Aprillan 5 Pieces Girls Hair Clip",
        price: 5000,
        discount: 60,
        qty: null,
        rating: 4,
        reviewCount: 26,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 3,
        categoryName: "accesories",
        stock: 8,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
        ],
    },
    {
        id: 8,
        imageSrc: "https://tse4.mm.bing.net/th/id/OIP.y-7VMhJcYOiXhUNNyJykvAAAAA?rs=1&pid=ImgDetMain&o=7&rm=3",
        name: "Handy Backpacks",
        price: 15000,
        discount: 0,
        qty: null,
        rating: 5,
        reviewCount: 453,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 4,
        categoryName: "bags",
        stock: 10,
        colors: [
            { name: "Amber", class: "bg-amber-900", selectedClass: "ring-gray-400" },
            { name: "Brown", class: "bg-amber-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
    },
    {
        id: 9,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/68/1996404/3.jpg?7538",
        name: "Leopard Skin Slide Sandal",
        price: 10000,
        discount: 10,
        qty: null,
        rating: 0,
        reviewCount: 2,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 1,
        categoryName: "shoes",
        stock: 2,
        sizes: [
            { name: "EU 36", inStock: false },
            { name: "EU 37", inStock: false },
            { name: "EU 38", inStock: false },
            { name: "EU 39", inStock: true },
            { name: "EU 40", inStock: true },
            { name: "EU 41", inStock: true },
            { name: "EU 42", inStock: false },
            { name: "EU 43", inStock: false },
        ],
    },
    {
        id: 10,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/43/898757/1.jpg?1362",
        name: " Unisex T- Shirt Round Neck",
        price: 17000,
        discount: 2,
        qty: null,
        rating: 5,
        reviewCount: 665,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 2,
        categoryName: "clothes",
        stock: 2,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
            { name: "Orange", class: "bg-orange-500", selectedClass: "ring-gray-400" },
            { name: "Blue", class: "bg-blue-700", selectedClass: "ring-gray-400" },
            { name: "Red", class: "bg-red-700", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "M", inStock: true },
            { name: "L", inStock: true },
            { name: "XL", inStock: true },
            { name: "XXL", inStock: true },
        ],
    },
    {
        id: 11,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/80/3711393/1.jpg?9979",
        name: "Aprillan Frameless Sunglasses",
        price: 5000,
        discount: 45,
        qty: null,
        rating: 4,
        reviewCount: 18,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 3,
        categoryName: "accesories",
        stock: 0,
    },
    {
        id: 12,
        imageSrc: "https://th.bing.com/th/id/R.f2a1c0802c6addcb616e6475bd0e7b68?rik=Wcj0WG%2bgdoKg2w&riu=http%3a%2f%2f2.bp.blogspot.com%2f-PUrOSuVpTNc%2fUiFW4fgG_YI%2fAAAAAAAAO4U%2f4xdgyNpTwKc%2fs1600%2fbag%2b4.jpg&ehk=kkr%2bi3FIied1wrgEBNVfUBvPndZeOtziTJZK3XSXTK0%3d&risl=&pid=ImgRaw&r=0",
        name: "Kate Spade Mini bBag",
        price: 12000,
        discount: 12,
        qty: null,
        rating: 3,
        reviewCount: 453,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 4,
        categoryName: "bags",
        stock: 10,
        colors: [
            { name: "Amber", class: "bg-amber-900", selectedClass: "ring-gray-400" },
            { name: "Brown", class: "bg-amber-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
    },
    {
        id: 13,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/26/9184202/1.jpg?6188",
        name: "Bowknot Heels ",
        price: 71000,
        discount: 13,
        qty: null,
        rating: 3,
        reviewCount: 9,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 1,
        categoryName: "shoes",
        stock: 2,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Red", class: "bg-red-500", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-black", selectedClass: "ring-gray-900" },
            { name: "Yellow", class: "bg-yellow-500", selectedClass: "ring-gray-400" },
            { name: "Green", class: "bg-green-500", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "EU 36", inStock: false },
            { name: "EU 37", inStock: true },
            { name: "EU 38", inStock: true },
            { name: "EU 39", inStock: true },
            { name: "EU 40", inStock: true },
            { name: "EU 41", inStock: true },
            { name: "EU 42", inStock: false },
            { name: "EU 43", inStock: false },
        ],
    },
    {
        id: 14,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/43/083997/1.jpg?0019",
        name: "Ladies High Waist Skinny Jean",
        price: 23000,
        discount: 15,
        qty: null,
        rating: 4,
        reviewCount: 39,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 2,
        categoryName: "clothes",
        stock: 2,
        colors: [
            { name: "Blue", class: "bg-blue-400", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-black", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "26", inStock: true },
            { name: "28", inStock: true },
            { name: "30", inStock: true },
            { name: "32", inStock: true },
            { name: "34", inStock: true },
            { name: "36", inStock: true },
            { name: "38", inStock: true },
            { name: "40", inStock: false },
        ],
    },
    {
        id: 15,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/32/0503412/1.jpg?5728",
        name: "Leather Short Zipper Wallet ",
        price: 5000,
        discount: 4,
        qty: null,
        rating: 5,
        reviewCount: 95,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 3,
        categoryName: "accesories",
        stock: 8,
        colors: [
            { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
            { name: "Pink", class: "bg-pink-400", selectedClass: "ring-gray-400" },
        ],
    },
    {
        id: 16,
        imageSrc: "https://tse4.mm.bing.net/th/id/OIP.XGN2knJwD-KnXAv6apXhhAHaJ4?rs=1&pid=ImgDetMain&o=7&rm=3",
        name: "Chanel Bag",
        price: 15000,
        discount: 0,
        qty: null,
        rating: 4,
        reviewCount: 3,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 4,
        categoryName: "bags",
        stock: 10,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Blue", class: "bg-blue-500", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
    },
    {
        id: 17,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/09/3380003/1.jpg?0866",
        name: "Outer Footwear Thick-soled",
        price: 6000,
        discount: 0,
        qty: null,
        rating: 4,
        reviewCount: 37,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 1,
        categoryName: "shoes",
        stock: 2,
        colors: [
            { name: "Purple", class: "bg-purple-700", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "EU 36", inStock: true },
            { name: "EU 37", inStock: true },
            { name: "EU 38", inStock: true },
            { name: "EU 39", inStock: true },
            { name: "EU 40", inStock: false },
            { name: "EU 41", inStock: false },
            { name: "EU 42", inStock: false },
            { name: "EU 43", inStock: false },
        ],
    },
    {
        id: 18,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/38/733668/1.jpg?1736",
        name: "Underwear Bra Tees",
        price: 6000,
        discount: 18,
        qty: null,
        rating: 4,
        reviewCount: 209,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 2,
        categoryName: "clothes",
        stock: 2,
        colors: [
            { name: "White", class: "bg-white", selectedClass: "ring-gray-400" },
            { name: "Gray", class: "bg-gray-200", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
        sizes: [
            { name: "S", inStock: true },
            { name: "M", inStock: true },
        ],
    },
    {
        id: 19,
        imageSrc: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/57/3200893/1.jpg?7950",
        name: "Reversible Satin Hair Bonne",
        price: 5000,
        discount: 0,
        qty: null,
        rating: 4,
        reviewCount: 99,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 3,
        categoryName: "accesories",
        stock: 8,
        colors: [
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
            { name: "Pink", class: "bg-pink-400", selectedClass: "ring-gray-400" },
            { name: "Orange", class: "bg-orange-500", selectedClass: "ring-gray-900" },
        ],
    },
    {
        id: 20,
        imageSrc: "https://tse3.mm.bing.net/th/id/OIP.0aVB2D28Lu_RRbQ97fTg2QHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
        name: "Zara Ladies Bag",
        price: 35000,
        discount: 5,
        qty: null,
        rating: 4.7,
        reviewCount: 53,
        description: "Key features: <br /> Thickness of waterproof platform: 0.5cm <br /> Upper material: PU <br /> Inner material: single layer Pu <br /> Color: white, black, gray <br /> Popular elements: Korean version, fashion, simplicity, spring and autumn women wears, delicate, thin, sexy.",
        detail: "Note: <br /> To maintain quality control we do personally inspect for each item prior to shipment .All items are 100% new and inspected.",
        categoryId: 4,
        categoryName: "bags",
        stock: 0,
        colors: [
            { name: "Amber", class: "bg-amber-900", selectedClass: "ring-gray-400" },
            { name: "Green", class: "bg-green-600", selectedClass: "ring-gray-400" },
            { name: "Black", class: "bg-gray-900", selectedClass: "ring-gray-900" },
        ],
    },
]

export { users, products }